export const INTERVIEW_PROBLEM_STATUS = {
  UNSOLVED: 'UNSOLVED',
  SOLVED: 'SOLVED',
};

export const INTERVIEW_STATUS = {
  CREATING: 'CREATING',
  PROCESSING: 'PROCESSING',
  PENDING: 'PENDING',
  DONE: 'DONE',
  ERROR: 'ERROR',
  ABORTED: 'ABORTED',
};
