export const INTERVIEW_PROBLEM_STATUS = {
  UNSOLVED: 'UNSOLVED',
  SOLVED: 'SOLVED',
};

export const INTERVIEW_STATUS = {
  PROCESSING: 'PROCESSING',
  PENDING: 'PENDING',
  DONE: 'DONE',
  ABORTED: 'ABORTED',
};
