name: "[CD] Deploy to Dev Server"

on:
  push:
    branches: [dev]

permissions:
  contents: write

jobs:
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      client: ${{steps.filter.outputs.client}}
      admin: ${{steps.filter.outputs.admin}}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          token: ${{ secrets.TOKEN }}
          filters: |
            client:
              - 'TIL-CLIENT/**'
            admin:
              - 'TIL-ADMIN/**'

  til-client-deploy:
    needs: changes
    if: ${{ needs.changes.outputs.client == 'true' }}
    uses: ./.github/workflows/cd-s3-deploy.yml
    secrets: inherit
    with:
      working_dir: TIL-CLIENT
      s3_bucket: ${{ secrets.DEV_S3_CLIENT_BUCKET_NAME }} 
      cloudfront: ${{ secrets.DEV_CLOUDFRONT_CLIENT_DISTRIBUTION_ID }} 
    env:
      VITE_PROFILE: dev
      VITE_TIL_API_URL: ${{ secrets.DEV_TIL_API_URL }}

  til-admin-deploy:
    needs: changes
    if: ${{ needs.changes.outputs.admin == 'true' }}
    uses: ./.github/workflows/cd-s3-deploy.yml
    secrets: inherit
    with:
      working_dir: TIL-ADMIN
      s3_bucket: ${{ secrets.DEV_S3_ADMIN_BUCKET_NAME }} 
      cloudfront: ${{ secrets.DEV_CLOUDFRONT_ADMIN_DISTRIBUTION_ID }} 
    env:
      VITE_PROFILE: dev
      VITE_TIL_ADMIN_API_URL: ${{ secrets.DEV_TIL_ADMIN_API_URL }}
