name: '[CD] Deploy to Dev Server'

on:
  push:
    branches: [dev]

jobs:
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      client: ${{steps.filter.outputs.client}}
      admin: ${{steps.filter.outputs.admin}}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          token: ${{ secrets.TOKEN }}
          filters: |
            client:
              - 'TIL-CLIENT/**'
            admin:
              - 'TIL-ADMIN/**'

  til-client-deploy:
    needs: changes
    if: ${{ needs.changes.outputs.client == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TIL-CLIENT
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Set environment variables
        run: |
          echo ${{ secrets.REACT_APP_PROFILE_VALUE }} >> $GITHUB_ENV
          echo ${{ secrets.REACT_APP_TIL_API_URL_VALUE }} >> $GITHUB_ENV

      - name: Build project
        run: |
          yarn install
          yarn build
      - name: Sync S3 bucket
        run: aws s3 sync ./build s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

  til-admin-deploy:
    needs: changes
    if: ${{ needs.changes.outputs.admin == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TIL-ADMIN
    steps:
      - name: TEMP echo
        run: echo 'til-admin todo'
