name: Reusable S3 Deploy

on:
  workflow_call:
    inputs:
      working_dir:
        required: true
        type: string
      s3_bucket:
        required: true
        type: string
      cloudfront:
        required: true
        type: string

jobs:
  s3-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_dir }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Build project
        run: |
          yarn install
          yarn build

      - name: Sync S3 bucket
        run: aws s3 sync ./dist s3://${{ inputs.s3_bucket }} --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ inputs.cloudfront }} --paths "/*"
