name: CI

on:
  push:
    branches:
      - dev

jobs:
  build-test-lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build

      - name: Run tests
        run: yarn test --passWithNoTests

      - name: Run formatter check
        run: yarn format

      - name: Run linter
        run: yarn lint
