name: CI

on:
  pull_request:
    branches: [ dev ]

permissions:
  contents: write

jobs:
  changes:
    name: Check for changes
    runs-on: ubuntu-latest
    outputs:
      client: ${{steps.filter.outputs.client}}
      admin: ${{steps.filter.outputs.admin}}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          token: ${{ secrets.TOKEN }}
          filters: |
            client:
              - 'TIL-CLIENT/**'
            admin:
              - 'TIL-ADMIN/**'

  til-client-check:
    needs: changes
    if: ${{ needs.changes.outputs.client == 'true' }}
    uses: ./.github/workflows/ci-build-test-lint-format.yml
    with:
      working_dir: TIL-CLIENT

  til-admin-check:
    needs: changes
    if: ${{ needs.changes.outputs.admin == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: TEMP echo
        run: echo 'til-admin todo'
#    uses: ./.github/workflows/ci-build-test-lint-format.yml
#    with:
#      working_dir: TIL-ADMIN
